# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.0 [current_project]
add_files C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_0/design_1_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_0/design_1_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_83M_0/design_1_rst_mig_7series_0_83M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_83M_0/design_1_rst_mig_7series_0_83M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_83M_0/design_1_rst_mig_7series_0_83M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/constrs_1/imports/xdc/design_1.xdc
set_property used_in_implementation false [get_files C:/Users/aksul/Documents/FPGA/7A35T_Arty_Ethernetlite_LwIP_VIV2015_2/IPI/project_1/project_1.srcs/constrs_1/imports/xdc/design_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
