# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/mb_server/mb_server.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server || ORIG_REF_NAME==mb_server}]

# IP: bd/mb_server/ip/mb_server_microblaze_0_0/mb_server_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_0 || ORIG_REF_NAME==mb_server_microblaze_0_0}]

# IP: bd/mb_server/ip/mb_server_dlmb_v10_0/mb_server_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_dlmb_v10_0 || ORIG_REF_NAME==mb_server_dlmb_v10_0}]

# IP: bd/mb_server/ip/mb_server_ilmb_v10_0/mb_server_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_ilmb_v10_0 || ORIG_REF_NAME==mb_server_ilmb_v10_0}]

# IP: bd/mb_server/ip/mb_server_dlmb_bram_if_cntlr_0/mb_server_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_server_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_server/ip/mb_server_ilmb_bram_if_cntlr_0/mb_server_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_server_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_server/ip/mb_server_lmb_bram_0/mb_server_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_lmb_bram_0 || ORIG_REF_NAME==mb_server_lmb_bram_0}]

# IP: bd/mb_server/ip/mb_server_microblaze_0_axi_periph_0/mb_server_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_server_microblaze_0_axi_periph_0}]

# IP: bd/mb_server/ip/mb_server_microblaze_0_axi_intc_0/mb_server_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_server_microblaze_0_axi_intc_0}]

# IP: bd/mb_server/ip/mb_server_microblaze_0_xlconcat_0/mb_server_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_server_microblaze_0_xlconcat_0}]

# IP: bd/mb_server/ip/mb_server_mdm_1_0/mb_server_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_mdm_1_0 || ORIG_REF_NAME==mb_server_mdm_1_0}]

# IP: bd/mb_server/ip/mb_server_clk_wiz_1_0/mb_server_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_clk_wiz_1_0 || ORIG_REF_NAME==mb_server_clk_wiz_1_0}]

# IP: bd/mb_server/ip/mb_server_rst_clk_wiz_1_100M_0/mb_server_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_server_rst_clk_wiz_1_100M_0}]

# IP: bd/mb_server/ip/mb_server_mig_7series_0_0/mb_server_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_mig_7series_0_0 || ORIG_REF_NAME==mb_server_mig_7series_0_0}]

# IP: bd/mb_server/ip/mb_server_axi_uartlite_0_0/mb_server_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_uartlite_0_0 || ORIG_REF_NAME==mb_server_axi_uartlite_0_0}]

# IP: bd/mb_server/ip/mb_server_axi_ethernetlite_0_0/mb_server_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_server_axi_ethernetlite_0_0}]

# IP: bd/mb_server/ip/mb_server_axi_timer_0_0/mb_server_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_timer_0_0 || ORIG_REF_NAME==mb_server_axi_timer_0_0}]

# IP: bd/mb_server/ip/mb_server_xbar_0/mb_server_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_xbar_0 || ORIG_REF_NAME==mb_server_xbar_0}]

# IP: bd/mb_server/ip/mb_server_rst_mig_7series_0_83M_0/mb_server_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==mb_server_rst_mig_7series_0_83M_0}]

# IP: bd/mb_server/ip/mb_server_auto_ds_0/mb_server_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_0 || ORIG_REF_NAME==mb_server_auto_ds_0}]

# IP: bd/mb_server/ip/mb_server_auto_pc_0/mb_server_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_pc_0 || ORIG_REF_NAME==mb_server_auto_pc_0}]

# IP: bd/mb_server/ip/mb_server_auto_cc_0/mb_server_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_cc_0 || ORIG_REF_NAME==mb_server_auto_cc_0}]

# IP: bd/mb_server/ip/mb_server_auto_ds_1/mb_server_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_1 || ORIG_REF_NAME==mb_server_auto_ds_1}]

# IP: bd/mb_server/ip/mb_server_auto_pc_1/mb_server_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_pc_1 || ORIG_REF_NAME==mb_server_auto_pc_1}]

# IP: bd/mb_server/ip/mb_server_auto_ds_2/mb_server_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_2 || ORIG_REF_NAME==mb_server_auto_ds_2}]

# IP: bd/mb_server/ip/mb_server_auto_pc_2/mb_server_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_pc_2 || ORIG_REF_NAME==mb_server_auto_pc_2}]

# IP: bd/mb_server/ip/mb_server_auto_ds_3/mb_server_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_3 || ORIG_REF_NAME==mb_server_auto_ds_3}]

# IP: bd/mb_server/ip/mb_server_auto_pc_3/mb_server_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_pc_3 || ORIG_REF_NAME==mb_server_auto_pc_3}]

# IP: bd/mb_server/ip/mb_server_auto_pc_4/mb_server_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_pc_4 || ORIG_REF_NAME==mb_server_auto_pc_4}]

# IP: bd/mb_server/ip/mb_server_auto_us_0/mb_server_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_us_0 || ORIG_REF_NAME==mb_server_auto_us_0}]

# IP: bd/mb_server/ip/mb_server_auto_us_1/mb_server_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_us_1 || ORIG_REF_NAME==mb_server_auto_us_1}]

# IP: bd/mb_server/ip/mb_server_auto_us_2/mb_server_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_auto_us_2 || ORIG_REF_NAME==mb_server_auto_us_2}]

# XDC: bd/mb_server/ip/mb_server_microblaze_0_0/mb_server_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_0 || ORIG_REF_NAME==mb_server_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_microblaze_0_0/mb_server_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mb_server/ip/mb_server_microblaze_0_0/mb_server_microblaze_0_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_dlmb_v10_0/mb_server_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_dlmb_v10_0 || ORIG_REF_NAME==mb_server_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_dlmb_v10_0/mb_server_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_ilmb_v10_0/mb_server_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_ilmb_v10_0 || ORIG_REF_NAME==mb_server_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_ilmb_v10_0/mb_server_ilmb_v10_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_dlmb_bram_if_cntlr_0/mb_server_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_ilmb_bram_if_cntlr_0/mb_server_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_lmb_bram_0/mb_server_lmb_bram_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_microblaze_0_axi_intc_0/mb_server_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_server_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_microblaze_0_axi_intc_0/mb_server_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_server_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_microblaze_0_axi_intc_0/mb_server_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_mdm_1_0/mb_server_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_mdm_1_0 || ORIG_REF_NAME==mb_server_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_mdm_1_0/mb_server_mdm_1_0_ooc_trace.xdc

# XDC: bd/mb_server/ip/mb_server_clk_wiz_1_0/mb_server_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_clk_wiz_1_0 || ORIG_REF_NAME==mb_server_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_clk_wiz_1_0/mb_server_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_clk_wiz_1_0 || ORIG_REF_NAME==mb_server_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_clk_wiz_1_0/mb_server_clk_wiz_1_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_rst_clk_wiz_1_100M_0/mb_server_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_server_rst_clk_wiz_1_100M_0}]

# XDC: bd/mb_server/ip/mb_server_rst_clk_wiz_1_100M_0/mb_server_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_server_rst_clk_wiz_1_100M_0}]

# XDC: bd/mb_server/ip/mb_server_rst_clk_wiz_1_100M_0/mb_server_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_mig_7series_0_0/mb_server_mig_7series_0_0/user_design/constraints/mb_server_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_mig_7series_0_0 || ORIG_REF_NAME==mb_server_mig_7series_0_0}]

# XDC: bd/mb_server/ip/mb_server_mig_7series_0_0/mb_server_mig_7series_0_0/user_design/constraints/mb_server_mig_7series_0_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_mig_7series_0_0/mb_server_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_mig_7series_0_0 || ORIG_REF_NAME==mb_server_mig_7series_0_0}]

# XDC: bd/mb_server/ip/mb_server_axi_uartlite_0_0/mb_server_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_axi_uartlite_0_0 || ORIG_REF_NAME==mb_server_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_axi_uartlite_0_0/mb_server_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_axi_uartlite_0_0/mb_server_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_axi_uartlite_0_0 || ORIG_REF_NAME==mb_server_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_server/ip/mb_server_axi_ethernetlite_0_0/mb_server_axi_ethernetlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_server_axi_ethernetlite_0_0}]

# XDC: bd/mb_server/ip/mb_server_axi_ethernetlite_0_0/mb_server_axi_ethernetlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_server_axi_ethernetlite_0_0}]

# XDC: bd/mb_server/ip/mb_server_axi_ethernetlite_0_0/mb_server_axi_ethernetlite_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_ethernetlite_0_0 || ORIG_REF_NAME==mb_server_axi_ethernetlite_0_0}]

# XDC: bd/mb_server/ip/mb_server_axi_ethernetlite_0_0/mb_server_axi_ethernetlite_0_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_axi_timer_0_0/mb_server_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_axi_timer_0_0 || ORIG_REF_NAME==mb_server_axi_timer_0_0}]

# XDC: bd/mb_server/ip/mb_server_axi_timer_0_0/mb_server_axi_timer_0_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_xbar_0/mb_server_xbar_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_rst_mig_7series_0_83M_0/mb_server_rst_mig_7series_0_83M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==mb_server_rst_mig_7series_0_83M_0}]

# XDC: bd/mb_server/ip/mb_server_rst_mig_7series_0_83M_0/mb_server_rst_mig_7series_0_83M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==mb_server_rst_mig_7series_0_83M_0}]

# XDC: bd/mb_server/ip/mb_server_rst_mig_7series_0_83M_0/mb_server_rst_mig_7series_0_83M_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_0/mb_server_auto_ds_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_0/mb_server_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_0 || ORIG_REF_NAME==mb_server_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_pc_0/mb_server_auto_pc_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_cc_0/mb_server_auto_cc_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_cc_0/mb_server_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_cc_0 || ORIG_REF_NAME==mb_server_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_ds_1/mb_server_auto_ds_1_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_1/mb_server_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_1 || ORIG_REF_NAME==mb_server_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_pc_1/mb_server_auto_pc_1_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_2/mb_server_auto_ds_2_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_2/mb_server_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_2 || ORIG_REF_NAME==mb_server_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_pc_2/mb_server_auto_pc_2_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_3/mb_server_auto_ds_3_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_ds_3/mb_server_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_ds_3 || ORIG_REF_NAME==mb_server_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_pc_3/mb_server_auto_pc_3_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_pc_4/mb_server_auto_pc_4_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_us_0/mb_server_auto_us_0_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_us_0/mb_server_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_us_0 || ORIG_REF_NAME==mb_server_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_us_1/mb_server_auto_us_1_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_us_1/mb_server_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_us_1 || ORIG_REF_NAME==mb_server_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/mb_server/ip/mb_server_auto_us_2/mb_server_auto_us_2_ooc.xdc

# XDC: bd/mb_server/ip/mb_server_auto_us_2/mb_server_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_server_auto_us_2 || ORIG_REF_NAME==mb_server_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/mb_server/mb_server_ooc.xdc
